# Clustering for UMAP-2D

# 1. Import Data

In [1]:
import pandas as pd
df = pd.read_csv("6. Clustering.csv")
print("The shape of df is", df.shape)
df.head()

The shape of df is (500, 4)


pdf_filename        X1         X2  \
0  1.2.276.0.75.2.5.80.25.3.190123133923759.93180...  9.966893   9.228810   
1  1.2.276.0.75.2.5.80.25.3.190123133924562.93180...  9.752504   9.033387   
2  1.2.276.0.75.2.5.80.25.3.190123134232237.93180...  9.121086  10.243672   
3  1.2.276.0.75.2.5.80.25.3.190123134234418.93180...  9.303379  10.575117   
4  1.2.276.0.75.2.5.80.25.3.190123134640676.93180...  7.134477   9.970622   

   normal  
0       0  
1       0  
2       1  
3       1  
4       0

# 2. Construct X and Y

In [34]:
X = df[["X1", "X2"]].to_numpy()
Y = df["normal"].to_numpy()
print("The shape of X is ", X.shape)
print("The shape of Y is ", Y.shape)

The shape of X is  (500, 2)
The shape of Y is  (500,)


# 3. Clustering
- k-means

In [118]:
from sklearn.cluster import KMeans

In [119]:
n_clusters = 2
kmeans = KMeans(n_clusters=n_clusters
                #, random_state=random_state
               );

### Make prediction ^_^

In [120]:
Y_pred = kmeans.fit_predict(X)
print("The length of Y_pred is", len(Y_pred))
Y_pred

The length of Y_pred is 500


array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,

# 4. Import other labels

In [152]:
label = pd.read_csv("gradings_agreement_raw.csv")
print("The shape of label is", label.shape)
label.head()

The shape of label is (500, 15)


pdf_filename  reliability  normal  \
0  1.2.276.0.75.2.5.80.25.3.190123133923759.93180...            1       0   
1  1.2.276.0.75.2.5.80.25.3.190123133924562.93180...            1       0   
2  1.2.276.0.75.2.5.80.25.3.190123134232237.93180...            1       1   
3  1.2.276.0.75.2.5.80.25.3.190123134234418.93180...            1       1   
4  1.2.276.0.75.2.5.80.25.3.190123134640676.93180...            1       0   

   gdefect1  gposition1  gdefect2  gposition2  gdefect3  gposition3  \
0         3           1         0           0         0           0   
1         3           1         0           0         0           0   
2         0           0         0           0         0           0   
3         0           0         0           0         0           0   
4         3           1         0           0         0           0   

   ngdefect1  ngposition1  ngdefect2  ngposition2  artifact1  artifact2  
0          0            0          0            0          0          0  
1          0            0          0            0          0          0  
2          0            0          0            0          0          0  
3          0            0          0            0          0          0  
4          0            0          0            0          0          0

### Make sure the orders are right!

In [122]:
label["pdf_filename"].compare(df["pdf_filename"])

Empty DataFrame
Columns: [self, other]
Index: []

In [123]:
label["normal"].compare(df["normal"])

Empty DataFrame
Columns: [self, other]
Index: []

# 5. Compare with other label

In [124]:
label["pred"] = Y_pred
print("The shape of label is", label.shape)
label.head()

The shape of label is (500, 16)


pdf_filename  reliability  normal  \
0  1.2.276.0.75.2.5.80.25.3.190123133923759.93180...            1       0   
1  1.2.276.0.75.2.5.80.25.3.190123133924562.93180...            1       0   
2  1.2.276.0.75.2.5.80.25.3.190123134232237.93180...            1       1   
3  1.2.276.0.75.2.5.80.25.3.190123134234418.93180...            1       1   
4  1.2.276.0.75.2.5.80.25.3.190123134640676.93180...            1       0   

   gdefect1  gposition1  gdefect2  gposition2  gdefect3  gposition3  \
0         3           1         0           0         0           0   
1         3           1         0           0         0           0   
2         0           0         0           0         0           0   
3         0           0         0           0         0           0   
4         3           1         0           0         0           0   

   ngdefect1  ngposition1  ngdefect2  ngposition2  artifact1  artifact2  pred  
0          0            0          0            0          0          0     1  
1          0            0          0            0          0          0     1  
2          0            0          0            0          0          0     1  
3          0            0          0            0          0          0     1  
4          0            0          0            0          0          0     1

1. normal
2. reliability
3. gdefect1
4. gdefect2
5. gdefect3
6. ngdefect1
7. ngdefect2
8. artifact1
9. artifact2

### 1. normal

In [125]:
# 1.
label["normal"].compare(label["pred"]).shape

(228, 2)

### 2. reliability

In [126]:
# 2. 
label["reliability"].compare(label["pred"]).shape

(200, 2)

### 3. gdefect1

In [127]:
# 3. 
label["gdefect1"].compare(label["pred"]).shape

(463, 2)

In [128]:
label["gdefect1"].unique()

array([ 3,  0,  2,  7,  4,  8, 11,  5,  9,  1, 12,  6, 10])

In [129]:
for i in range(len(label["gdefect1"])):
    if label["gdefect1"][i] == 0:
        label["gdefect1"][i] = 0
    else: 
        label["gdefect1"][i] = 1
        
label["gdefect1"].unique()

/Users/yuhuicao/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/yuhuicao/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([1, 0])

In [130]:
label["gdefect1"].compare(label["pred"]).shape

(280, 2)

### 4. gdefect2

In [131]:
# 4. 
label["gdefect2"].compare(label["pred"]).shape

(422, 2)

In [132]:
label["gdefect2"].unique()

array([ 0,  5,  3,  4,  1, 10,  7,  2])

In [133]:
for i in range(len(label["gdefect2"])):
    if label["gdefect2"][i] == 0:
        label["gdefect2"][i] = 0
    else: 
        label["gdefect2"][i] = 1
        
label["gdefect2"].unique()

/Users/yuhuicao/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/yuhuicao/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


array([0, 1])

In [134]:
# 4. 
label["gdefect2"].compare(label["pred"]).shape

(374, 2)

### 5. gdefect3

In [135]:
# 5. 
label["gdefect3"].compare(label["pred"]).shape

(414, 2)

In [136]:
label["gdefect3"].unique()

array([0, 3, 6, 5, 4, 7, 2])

In [137]:
for i in range(len(label["gdefect3"])):
    if label["gdefect3"][i] == 0:
        label["gdefect3"][i] = 0
    else: 
        label["gdefect3"][i] = 1
        
label["gdefect3"].unique()

/Users/yuhuicao/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/yuhuicao/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


array([0, 1])

In [138]:
# 5. 
label["gdefect3"].compare(label["pred"]).shape

(401, 2)

### 6. ngdefect1

In [139]:
# 6. 
label["ngdefect1"].compare(label["pred"]).shape

(420, 2)

In [140]:
label["ngdefect1"].unique()

array([0, 5, 4, 1, 3])

In [141]:
for i in range(len(label["ngdefect1"])):
    if label["ngdefect1"][i] == 0:
        label["ngdefect1"][i] = 0
    else: 
        label["ngdefect1"][i] = 1
        
label["ngdefect1"].unique()

/Users/yuhuicao/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/yuhuicao/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


array([0, 1])

In [142]:
# 6. 
label["ngdefect1"].compare(label["pred"]).shape

(407, 2)

### 7. ngdefect2

In [143]:
# 7. 
label["ngdefect2"].compare(label["pred"]).shape
##### No information~~~~

(413, 2)

In [144]:
label["ngdefect2"].unique()

array([0])

### 8. artifact1

In [145]:
# 8. 
label["artifact1"].compare(label["pred"]).shape

(412, 2)

In [146]:
label["artifact1"].unique()

array([0, 4, 2, 5, 1])

In [147]:
for i in range(len(label["artifact1"])):
    if label["artifact1"][i] == 0:
        label["artifact1"][i] = 0
    else: 
        label["artifact1"][i] = 1
        
label["artifact1"].unique()

/Users/yuhuicao/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/yuhuicao/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


array([0, 1])

In [148]:
# 8. 
label["artifact1"].compare(label["pred"]).shape

(405, 2)

### 9. artifact2

In [154]:
# 9. 
label["artifact2"].compare(label["pred"]).shape
##### No information~~~~

KeyError: 'pred'

In [150]:
label["artifact2"].unique()

array([0])

# ngdefect1 vs. artifact1 are almost the same

In [153]:
print("The shape of difference is", label["ngdefect1"].compare(label["artifact1"]).shape)
label["ngdefect1"].compare(label["artifact1"])

The shape of difference is (29, 2)


self  other
55    0.0    4.0
72    0.0    2.0
86    5.0    0.0
94    4.0    0.0
135   4.0    0.0
189   5.0    0.0
195   4.0    0.0
200   0.0    4.0
201   0.0    4.0
210   1.0    0.0
276   1.0    0.0
280   5.0    2.0
290   1.0    0.0
299   5.0    0.0
323   0.0    5.0
325   0.0    5.0
333   5.0    0.0
344   5.0    0.0
356   3.0    0.0
358   4.0    0.0
400   5.0    0.0
410   0.0    1.0
416   1.0    0.0
426   5.0    0.0
429   5.0    0.0
442   5.0    0.0
443   1.0    0.0
455   1.0    0.0
476   3.0    0.0